apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-db-{{ environment }}
  namespace: {{ namespace }}
spec:
  selector:
    app: {{ name }}-db-{{ environment }}
  type: {{ service_type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: {{ name }}-db-{{ environment }}
    protocol: TCP
    port: 5432
    targetPort: 5432
